# Generated by Django 2.2.13 on 2021-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210604_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='post',
            field=models.TextField(max_length=255),
        ),
    ]
